### ISSUE TITLE
What is the purpose for 'eosio.code'?

### ISSUE THREAD

**Issue by bobxuyang** [Dappub/signupeoseos#3]
can not run this command: cleos set account permission signupeoseos active '{"threshold": 1,"keys": [{"key": "your_public_key","weight": 1}],"accounts": [{"permission":{"actor":"signupeoseos","permission":"eosio.code"},"weight":1}]}' owner -p signupeoseos

**Comment by xJonathanLEI** [comment]
This is due to a change in EOS's permission system. Now, by default, the code running in a contract no longer carries anyone's **active** permission (not even that of the contract itself). Instead, a contract would only carry a special permission called "eosio.code" of itself.

In the case of signupeoseos, the contract helps the user buy system resources, which would require signupeoseos@active, but the code running has signupeoseos@eosio.code only. That's why we're giving *eosio.code* the weight needed to pass the *active* permission.

**Comment by onigirisan** [comment]
thanks @xJonathanLEI, nice explanation, I'm going to close this issue then
